---
title: ''
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load required packages
library(jsonlite)
library(tidyverse)
library(keyring)
library(janitor)

#get list of zctas in cook
cook_zctas <- read_csv(paste0(getwd(), "/2020/decennial-2020-total-zcta.csv")) %>% pull(geoid_zcta)

#set url for current api 
census_api <- "https://api.census.gov/data/2020/dec/dhc"
#census_api <- "https://api.census.gov/data/2010/dec/sf1"

#load in variable names to match with codes
dec_vars <- fromJSON(paste0(census_api, "/variables")) %>%
  as.data.frame() %>%
  row_to_names(row_number = 1)

```

## Pull table P12 (sex by age) from decennial for all Cook ZCTAs; Total Pop and Pop in Cook

```{r zcta_age}

#Create empty list to store place data
dec_age_pops_zcta_list <- list()

#loop through zcta list to pull data
for (i in 1:length(cook_zctas)) {
  
  api <- paste0(census_api,"?get=NAME,group(P12)&for=zip%20code%20tabulation%20area:", cook_zctas[[i]], "&key=", key_get("census-api-key"))
  
  #pull data
  zcta_pull <- fromJSON(api) %>% 
    as.data.frame() %>%
    row_to_names(row_number = 1) %>%
    pivot_longer(cols = -NAME, names_to = "variable", values_to = "estimate") %>%
    filter(grepl("^P.*", variable)) %>%    #keep only population estimates, no meta data
    filter(!grepl(".*ERR$|.*NA", variable)) %>%
    left_join(dec_vars, by = c("variable" = "name")) %>%   #link back to list of variables for label to ensure expected variables are pulled
    mutate(estimate = as.numeric(as.character(estimate)))  #numbers being stored as factors
  
  #add results to list
  dec_age_pops_zcta_list[[i]] <- zcta_pull
  
}

#combine separate town files into one
dec_age_pops_zcta <- bind_rows(dec_age_pops_zcta_list)

#clean file
dec_age_pops_zcta_clean <- dec_age_pops_zcta %>%
  filter(!grepl(".*:$", label)) %>%  #remove total pop, total male, total female 
  mutate(label = trimws(str_remove(label, "!!Total:!!"))) %>%
  separate(label, into = c("sex", "age"), sep = ":!!") %>%
  mutate(geoid_zcta = as.numeric(gsub("^.* ", "", NAME))) %>%
  select(geoid_zcta,
         variable,
         sex,
         age,
         total_pop = estimate)


#REPEAT FOR POP IN COOK

#Create empty list to store place data - cook
dec_age_pops_zcta_list_cook <- list()

#loop through zcta list to pull data - cook
for (i in 1:length(cook_zctas)) {
  
  api <- paste0(census_api, "?get=NAME,group(P12)&for=county%20(or%20part):031&in=state:17%20zip%20code%20tabulation%20area%20(or%20part):", cook_zctas[[i]], "&key=", key_get("census-api-key"))
  
  #pull data
  zcta_pull <- fromJSON(api) %>% 
    as.data.frame() %>%
    row_to_names(row_number = 1) %>%
    pivot_longer(cols = -NAME, names_to = "variable", values_to = "pop_in_cook") %>%
    filter(grepl("^P.*", variable)) %>%    #keep only population estimates, no meta data
    filter(!grepl(".*ERR$|.*NA", variable)) %>%
    left_join(dec_vars, by = c("variable" = "name")) %>%   #link back to list of variables for label to ensure expected variables are pulled
    mutate(pop_in_cook = as.numeric(as.character(pop_in_cook)))  #numbers being stored as factors
  
  #add results to list
  dec_age_pops_zcta_list_cook[[i]] <- zcta_pull
  
}

#combine separate files into one - cook
dec_age_pops_zcta_cook <- bind_rows(dec_age_pops_zcta_list_cook) %>%
  mutate(geoid_zcta = as.numeric(str_extract(NAME,"(?<=ZCTA5 ).*(?=, Illinois)"))) %>%
  select(geoid_zcta, variable, pop_in_cook)

#create final file
dec_age_pops_zcta_clean_final <- dec_age_pops_zcta_clean %>%
  left_join(dec_age_pops_zcta_cook)

#save
write_csv(dec_age_pops_zcta_clean_final, paste0(getwd(),"/2020/decennial-2020-age-sex-by-zcta.csv"))

```

## Pull table P14 (single age years under 20) from decennial 2010 summary file 1 for all Cook ZCTAs

```{r zcta_under_20}


#Create empty list to store place data
dec_under_20_pops_zcta_list <- list()

#loop through zcta list to pull data
for (i in 1:length(cook_zctas)) {
  
  api <- paste0("https://api.census.gov/data/2010/dec/sf1?get=NAME,group(P14)&for=zip%20code%20tabulation%20area:", cook_zctas[[i]], "&key=", key_get("census-api-key"))
  
  #pull data
  zcta_pull <- fromJSON(api) %>% 
    as.data.frame() %>%
    row_to_names(row_number = 1) %>%
    pivot_longer(cols = -NAME, names_to = "variable", values_to = "estimate") %>%
    filter(grepl("^P.*", variable)) %>%    #keep only population estimates, no meta data
    filter(!grepl(".*ERR$", variable)) %>%
    left_join(dec_vars, by = c("variable" = "name")) %>%   #link back to list of variables for label to ensure expected variables are pulled
    mutate(estimate = as.numeric(as.character(estimate)))  #numbers being stored as factors
  
  #add results to list
  dec_under_20_pops_zcta_list[[i]] <- zcta_pull
  
}

#combine separate town files into one
dec_under_20_pops_zcta <- bind_rows(dec_under_20_pops_zcta_list)

dec_under_20_pops_zcta_clean <- dec_under_20_pops_zcta %>%
  filter(!label %in% c("Total", "Total!!Male", "Total!!Female"))  %>% #remove total pop, total male, total female 
  mutate(label = gsub("Total!!", "", label)) %>%
  separate(label, into = c("sex", "age"), sep = "!!") %>%
  mutate(zcta = as.numeric(gsub("^.* ", "", NAME))) %>%
  select(zcta,
         variable,
         sex,
         age,
         estimate)

write_csv(dec_under_20_pops_zcta_clean, "decennial-2010-under-20-single-year-age-by-zcta.csv")

#Rename estimate variable to make it clear total pop (not pop in cook was pulled)

dec_under_20_pops_zcta_clean <- read_csv("decennial-2010-under-20-single-year-age-by-zcta.csv") %>%
  rename(total_pop = estimate)

write_csv(dec_under_20_pops_zcta_clean, "decennial-2010-under-20-single-year-age-by-zcta.csv")

```

## Pull table P11 (ethnicity by race) from decennial for all Cook ZCTAs; Total Pop and Pop in Cook

(formally table P5)

```{r zcta_race}

#Get mutually exclusive categories of interest
race_vars <- dec_vars %>%
  filter(grepl("P11.*N$", name)) %>%  #get all race/eth vars
  filter(!grepl("races:!", label)) %>%  #filter out 2+ races sub-categories
  filter(grepl("races:$", label) | grepl(".*[a-z]$", label))  %>% #filter out totals so only mutually exclusive remain
  mutate(race_eth = case_when(grepl("two", label) ~ "Non-Hispanic Two or More Races",
                              grepl("White", label) ~ "Non-Hispanic White",
                              grepl("Black", label) ~ "Non-Hispanic Black",
                              grepl("Asian", label) ~ "Non-Hispanic Asian",
                              grepl("Alaska", label) ~ "Non-Hispanic American Indian or Alaska Native",
                              grepl("Hawaiian", label) ~ "Non-Hispanic Native Hawaiian or Other Pacific Islander",
                              grepl("Other", label) ~ "Non-Hispanic Other",
                              TRUE ~ "Hispanic or Latino")) %>%
  select(variable = name, race_eth)

#Create empty list to store place data
dec_race_pops_zcta_list <- list()

#loop through zcta list to pull data
for (i in 1:length(cook_zctas)) {
  
  api <- paste0(census_api,"?get=NAME,group(P11)&for=zip%20code%20tabulation%20area:", cook_zctas[[i]], "&key=", key_get("census-api-key"))
  
  #pull data
  zcta_pull <- fromJSON(api) %>% 
    as.data.frame() %>%
    row_to_names(row_number = 1) %>%
    pivot_longer(cols = -NAME, names_to = "variable", values_to = "total_pop") %>%
    filter(grepl("^P.*", variable)) %>%    #keep only population estimates, no meta data
    filter(!grepl(".*ERR$|.*NA", variable)) %>%
    left_join(dec_vars, by = c("variable" = "name")) %>%   #link back to list of variables for label to ensure expected variables are pulled
    mutate(total_pop = as.numeric(as.character(total_pop)))  #numbers being stored as factors
  
  #add results to list
  dec_race_pops_zcta_list[[i]] <- zcta_pull
  
}

#combine separate town files into one
dec_race_pops_zcta <- bind_rows(dec_race_pops_zcta_list)

#clean file
dec_race_pops_zcta_clean <- dec_race_pops_zcta %>%
  left_join(race_vars) %>%
  drop_na(race_eth) %>%
  mutate(geoid_zcta = as.numeric(gsub("^.* ", "", NAME))) %>%
  select(geoid_zcta,
         variable,
         race_eth,
         total_pop)


#REPEAT FOR POP IN COOK

#Create empty list to store place data - cook
dec_race_pops_zcta_list_cook <- list()

#loop through zcta list to pull data - cook
for (i in 1:length(cook_zctas)) {
  
  api <- paste0(census_api, "?get=NAME,group(P11)&for=county%20(or%20part):031&in=state:17%20zip%20code%20tabulation%20area%20(or%20part):", cook_zctas[[i]], "&key=", key_get("census-api-key"))
  
  #pull data
  zcta_pull <- fromJSON(api) %>% 
    as.data.frame() %>%
    row_to_names(row_number = 1) %>%
    pivot_longer(cols = -NAME, names_to = "variable", values_to = "pop_in_cook") %>%
    filter(grepl("^P.*", variable)) %>%    #keep only population estimates, no meta data
    filter(!grepl(".*ERR$|.*NA", variable)) %>%
    left_join(dec_vars, by = c("variable" = "name")) %>%   #link back to list of variables for label to ensure expected variables are pulled
    mutate(pop_in_cook = as.numeric(as.character(pop_in_cook)))  #numbers being stored as factors
  
  #add results to list
  dec_race_pops_zcta_list_cook[[i]] <- zcta_pull
  
}

#combine separate files into one - cook
dec_race_pops_zcta_cook <- bind_rows(dec_race_pops_zcta_list_cook) %>%
  mutate(geoid_zcta = as.numeric(str_extract(NAME,"(?<=ZCTA5 ).*(?=, Illinois)"))) %>%
  select(geoid_zcta, variable, pop_in_cook)

#create final file
dec_race_pops_zcta_clean_final <- dec_race_pops_zcta_clean %>%
  left_join(dec_race_pops_zcta_cook)

#save
write_csv(dec_race_pops_zcta_clean_final, paste0(getwd(),"/2020/decennial-2020-race-ethnicity-by-zcta.csv"))

```
