---
title: ''
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load required packages
library(jsonlite)
library(tidyverse)
library(keyring)
library(janitor)

#store your census api key - only needs to be done once per computer
#key_set("census-api-key")

#set api string
census_api <- "https://api.census.gov/data/2020/acs/acs5"
vintage <- "2020 5 YR"
end_year <- 2020

#load in current munis
munis <- read_csv("https://github.com/Cook-County-Department-of-Public-Health/ccdph-data-sets/blob/main/2020/decennial-2020-total-muni.csv?raw=TRUE")
place_codes <- munis %>% pull(census_place_code) 

#load in current zctas
zctas <- read_csv("https://github.com/Cook-County-Department-of-Public-Health/ccdph-data-sets/blob/main/cook-county-zip-codes.csv?raw=TRUE") %>%
  drop_na(zcta) %>%
  pull(zcta) %>%
  unique() %>%
  as.character()

#load in ACS variable names to match with codes
acs_vars <- fromJSON(paste0(census_api,"/variables")) %>%
  as.data.frame() %>%
  row_to_names(row_number = 1)
  
```

## Function to pull muni data

```{r}
#function arguments:
#geo_type - quoted character, either "muni" or "zcta"
#place_code - quoted character, the census place code for munis
#variable - quoted character, the variable or table you want to pull
#group - logical, set to T if pulling a table, F if pulling single variable
#pop_in_cook - logical, pull only pop within Cook by default, change to F if you want total pops for partial towns
#NOTE: census_api must exist in global environment
get_small_geo_pops_acs <- function(geo_type, place_code, variable, group, pop_in_cook = T){
  
  #construct api from arguments
  variable_param <- ifelse(group, paste0("group(", variable,")"), variable)
  
  geo_param <- case_when(geo_type == "muni" & pop_in_cook ~ paste0("&for=county%20(or%20part):031&in=state:17%20place:", place_code),
                         geo_type == "muni" & pop_in_cook == F ~ paste0("&for=place:", place_code, "&in=state:17"),
                         geo_type == "zcta" & pop_in_cook == F ~ paste0("&for=zip%20code%20tabulation%20area:", place_code))
  
  #partial zctas not available in ACS, return error if selected
  if (geo_type == "zcta" & pop_in_cook) {return("Partial ZCTA populations are not available in ACS surveys. Please revise your function arguments.")}
  
  # if (pop_in_cook) {
  #   api <- paste0(census_api,"?get=NAME,GEO_ID,", variable_param, "&for=county%20(or%20part):031&in=state:17%20place:", place_code, "&key=", key_get("census-api-key"))
  # } else {
  #   api <- paste0(census_api,"?get=NAME,GEO_ID,", variable_param, "&for=place:", place_code, "&in=state:17&key=", key_get("census-api-key"))
  # }
  api <- paste0(census_api, "?get=NAME,GEO_ID,", variable_param, geo_param, "&key=", key_get("census-api-key"))
  
  #pull census data
  results <- try(fromJSON(api))
  
  #stop function if URL doesn't return anything
  if (class(results) == "try-error") {
    #stop(paste("The API call failed at place code", place_code))
    return(paste("The API call failed for place code", place_code))
  }
  
  #clean data
  town_pull <- results %>% 
    as.data.frame() %>%
    row_to_names(row_number = 1) %>%
    pivot_longer(cols = -c(NAME, GEO_ID), names_to = "variable", values_to = "estimate") %>%
    filter(grepl("*(E|M)$", variable)) %>%    #keep only population estimates and MOEs (see note below, no annonations present)
    separate(variable, into = c("variable", "estimate_type"), sep = -1) %>%
    pivot_wider(c(NAME, variable), names_from = estimate_type, values_from = estimate) %>%
    rename(estimate = E, moe = M) %>%
    mutate(variable = paste0(variable, "E")) %>%
    left_join(acs_vars, by = c("variable" = "name")) %>%   #link back to acs list of variables for label to ensure expected variables are pulled
    mutate(census_place_code = as.character(place_code)) %>%
    mutate(estimate = as.numeric(as.character(estimate))) 
  
  return(town_pull)
  
}

```

## Pull table B01001 (sex by age) from 5 year ACS for all CCDPH municipalities

```{r acs_muni_age_sex}

#Pull total population for all Cook munis
acs_muni_age_sex_total <- map(place_codes, ~get_small_geo_pops_acs(place_code = .x, geo_type = "muni", variable = "B01001", group = T, pop_in_cook = F)) %>% 
  discard(inherits, "character") %>%  
  bind_rows()

#Pull population in Cook for all Cook munis
#Note: #if interested in seeing failures, change discard() to keep() and drop bind_rows
acs_muni_age_sex_cook <- map(place_codes, ~get_small_geo_pops_acs(place_code = .x,  geo_type = "muni", variable = "B01001", group = T)) %>%
  discard(inherits, "character") %>%  
  bind_rows()

#combine files and create variables
acs_muni_age_sex_final <- acs_muni_age_sex_total %>%
  rename(total_pop = estimate, total_pop_moe = moe) %>%
  left_join(select(acs_muni_age_sex_cook, variable, census_place_code, pop_in_cook = estimate, pop_in_cook_moe = moe), 
            by = c("variable", "census_place_code")) %>%
  left_join(select(munis, municipality, census_place_code)) %>%
  filter(!variable %in% c("B01001_001E", "B01001_002E", "B01001_026E"))  %>% #remove totals
  mutate(label = gsub("Estimate!!Total:!!", "", label)) %>%
  separate(label, into = c("sex", "age"), sep = ":!!") %>%
  mutate(pop_in_cook = replace_na(pop_in_cook, 0),
         vintage = vintage) %>%
  select(census_name = NAME,
         clean_name = municipality,
         census_place_code,
         variable,
         sex,
         age,
         contains("total_pop"),
         contains("pop_in_cook"),
         vintage)

#save data
write_csv(acs_muni_age_sex_final, paste0(getwd(),"/acs/acs-5yr-age-sex-by-muni.csv"))

```

## Pull table B01001 (sex by age) from 5 year ACS for all cook zctas

```{r acs_zcta_age_sex}

#Pull total population for all Cook zctas (partial not available in ACS)
acs_zcta_age_sex_total <- map(zctas, ~get_small_geo_pops_acs(place_code = .x, geo_type = "zcta", variable = "B01001", group = T, pop_in_cook = F)) %>% 
  discard(inherits, "character") %>%  
  bind_rows()

#create variables
acs_zcta_age_sex_final <- acs_zcta_age_sex_total %>%
  rename(total_pop = estimate, total_pop_moe = moe) %>%
  filter(!variable %in% c("B01001_001E", "B01001_002E", "B01001_026E"))  %>% #remove totals
  mutate(label = gsub("Estimate!!Total:!!", "", label)) %>%
  separate(label, into = c("sex", "age"), sep = ":!!") %>%
  mutate(vintage = vintage) %>%
  select(zcta = census_place_code,
         variable,
         sex,
         age,
         contains("total_pop"),
         vintage)

#save data
write_csv(acs_zcta_age_sex_final, paste0(getwd(),"/acs/acs-5yr-age-sex-by-zcta.csv"))

```

## Pull jurisdiction age populations using tidycensus since functions already written

```{r acs_jurisdiction_age_totals}

#modified from old Hannah code

library(tidycensus)
census_api_key(key_get("census-api-key"))

#function to get ACS data using tidycensus
ccdph_acs_population = function(variable, year = end_year, survey = "acs5", geography = "ccdph"){  #alt for geography is "scc"
  
  all_cook  = get_acs(geography = "county", survey = survey,
                                             state = "IL", county = "Cook",
                                             year = year, variables = variable) %>%
    pull(estimate)
  
  all_places = get_acs(geography = "place",  survey = survey,
                                        state = "IL", 
                                        year = year, variables = variable)
  
  ooj_munis = all_places %>%
    filter(NAME %in% c("Evanston city, Illinois",
                       "Skokie village, Illinois",
                       "Oak Park village, Illinois"
    )) %>%
    pull(estimate) %>%
    sum()
  
  ooj_chicago = all_places %>%
    filter(NAME %in% c("Chicago city, Illinois"
    )) %>%
    pull(estimate) %>%
    sum()
  
  ooj_stickney  = get_acs(geography = "county subdivision",  survey = survey,
                                         state = "IL", county = "Cook",
                                         year = year, variables = variable) %>%
    filter(NAME == "Stickney township, Cook County, Illinois") %>%
    pull(estimate)
  
  if (geography == "ccdph") {
    ccdph = all_cook - ooj_munis - ooj_chicago - ooj_stickney
    return(ccdph)
  } else {
    scc = all_cook - ooj_chicago
    return(scc)
  }
  

  
}

#load all variables from tidy
vars = load_variables(end_year, "acs5", cache = TRUE)

#id age variables
age_vars_acs_table = vars %>% 
  filter(concept == "SEX BY AGE",
         !(label %in% c("Estimate!!Total:", "Estimate!!Total:!!Male:", 
                        "Estimate!!Total:!!Female:"))
         ) 
age_vars_acs = age_vars_acs_table$name
names(age_vars_acs) = age_vars_acs_table$label

#get estimates for ccdph from tidy using fx above
age_pops_acs_ccdph = sapply(age_vars_acs, ccdph_acs_population)

#get estimates for ccdph from tidy using fx above
age_pops_acs_scc= map(age_vars_acs, ~ccdph_acs_population(.x, geography = "scc"))

#clean scc
age_pops_scc_clean <- age_pops_acs_scc %>%
  bind_rows %>%
  pivot_longer(cols = everything(), names_to = "age", values_to = "scc_pop")

#clean dataset ccdph and create final
age_pops_acs_final <- age_pops_acs_ccdph %>%
  bind_cols(names(.), .) %>%
  magrittr::set_colnames(c("age", "ccdph_pop")) %>%
  full_join(age_pops_scc_clean) %>%
  mutate(age = gsub("^.*\\!\\!", "", age)) %>%
  group_by(age) %>%
  summarise(ccdph_pop = sum(ccdph_pop),
            scc_pop = sum(scc_pop)) %>%
  ungroup() %>%
  mutate(vintage = vintage) %>%
  mutate(age = factor(age, ordered = T),
         age = fct_relevel(age, c("Under 5 years", "5 to 9 years"), after = 0)) %>%
  arrange(age)

write_csv(age_pops_acs_final, paste0(getwd(),"/acs/acs-5yr-age-sex.csv"))


#code added later - Nov 2022 - to add chicago to file
chicago_age_sex <- fromJSON(paste0(census_api, "?get=NAME,GEO_ID,group(B01001)&for=place:14000&in=state:17&key=", key_get("census-api-key"))) %>% 
  as.data.frame() %>%
  row_to_names(row_number = 1) %>%
  pivot_longer(cols = -c(NAME, GEO_ID), names_to = "variable", values_to = "estimate") %>%
  filter(grepl("*(E)$", variable)) %>%    #this file only has estimates, consider reformatting in next pull to keep MOEs
  left_join(acs_vars, by = c("variable" = "name")) %>%   #link back to acs list of variables for label to ensure expected variables are pulled
  mutate(age_c = gsub("^.*\\!\\!", "", label),
         estimate = as.numeric(estimate)) %>%
  filter(!grepl(":", age_c)) %>%
  group_by(age_c) %>%
  summarise(chicago_pop = sum(estimate)) %>%
  ungroup() %>%
  mutate(age_c = factor(age_c, ordered = T),
         age_c = fct_relevel(age_c, c("Under 5 years", "5 to 9 years"), after = 0)) %>%
  arrange(age_c)

age_pops_acs_final <- read_csv(paste0(getwd(),"/acs/acs-5yr-age-sex.csv")) %>%
  cbind(chicago_age_sex) %>%
  select(age, ccdph_pop, scc_pop, chicago_pop, vintage)

write_csv(age_pops_acs_final, paste0(getwd(),"/acs/acs-5yr-age-sex.csv"))

```

## Get select SES variables for munis

```{r ses}

#unemployment - B23025_005 for numerator, B23025_002 for denominator (in civilian labor force, unemployed; universe 16+)
acs_muni_unemployment_cook <- map(place_codes, ~get_small_geo_pops_acs(place_code = .x,  geo_type = "muni", variable = "B23025", group = T)) %>%
  discard(inherits, "character") %>%  
  bind_rows()

acs_muni_unemployment_cook_rate <- acs_muni_unemployment_cook %>%
  filter(variable %in% c("B23025_005E", "B23025_002E")) %>%
  select(census_place_code, variable, estimate) %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  mutate(unemploy_rt = round(B23025_005E / B23025_002E * 100, 1)) %>%
  left_join(munis) %>%
  filter(district != "OOJ" & exclude_from_analysis == F) %>%
  select(municipality, census_place_code, district, unemploy_rt)

#uninsured - group B27001, no health insurance vars (universe civilian non-institutional)
acs_muni_uninsured_cook <- map(place_codes, ~get_small_geo_pops_acs(place_code = .x,  geo_type = "muni", variable = "B27001", group = T)) %>%
  discard(inherits, "character") %>%  
  bind_rows()

acs_muni_uninsured_cook_rate <- acs_muni_uninsured_cook %>%
  filter(variable == "B27001_001E" | grepl("No health insurance", label)) %>%
  group_by(census_place_code) %>%
  summarise(total = estimate[variable == "B27001_001E"],
            num_uninsured = sum(estimate[variable != "B27001_001E"])) %>%
  ungroup() %>%
  mutate(uninsure_rt = round(num_uninsured / total * 100, 1))

#percent no high school, group B15001 (universe 18+)
acs_muni_education_cook <- map(place_codes, ~get_small_geo_pops_acs(place_code = .x,  geo_type = "muni", variable = "B15001", group = T)) %>%
  discard(inherits, "character") %>%  
  bind_rows()

acs_muni_education_cook_rate <- acs_muni_education_cook %>%
  filter(variable == "B15001_001E" | grepl("9th", label)) %>%
  group_by(census_place_code) %>%
  summarise(total = estimate[variable == "B15001_001E"],
            num_no_hs = sum(estimate[variable != "B15001_001E"])) %>%
  ungroup() %>%
  mutate(no_hs_rt = round(num_no_hs / total * 100, 1))

#combined_file
acs_ses_cook_rt <- acs_muni_unemployment_cook_rate %>%
  left_join(acs_muni_uninsured_cook_rate, by = "census_place_code") %>%
  left_join(acs_muni_education_cook_rate, by = "census_place_code") %>%
  select(municipality, district, contains("rt"))

write_csv(acs_ses_cook_rt, "C:/Users/Kelley/Downloads/acs_ses_rts.csv")

```

